### ISSUE TITLE
Question about example code for reading counter data from tables

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime-shell#103]
This documentation file: https://github.com/p4lang/p4runtime-shell/blob/main/usage/read_table_entry_counter.md

contains the following example Python code for reading the counter data from a table:
```
P4Runtime sh >>> ########################## Retrieve all table entries and print out counter_data (byte and packet counts)
            ...: ########################## (Note: you HAVE to generate traffic on some table entries to see non-zero counters)
            ...:
            ...: for te in table_entry['ingress.table0_control.table0'].read():
            ...:       # You HAVE to set some te.counter_data field to trigger reading out the counter_data
            ...:       te.counter_data.byte_count = 0
            ...:       for x in te.read():
            ...:             if x.counter_data.byte_count == 0:
            ...:                   print('te.counter_data.byte_count == 0 -> Generate some traffic before reading out the counters')
            ...:             else:
            ...:                   print('Counter data', x.counter_data)
            ...:
```
Can you comment on why there is a nested `for` loop here?  It appears that the outer loop is iterating over all entries in the table `ingress.table0_control.table0`.  True?

For some reason, I guess that outer `.read()` call is getting the match fields, action, and action parameters of the entry, but is not getting the counter data.

Then the inner `for` loop is reading the entry again, in a way that it will read the counter data this time.  That inner `for` loop is only reading one entry, but `.read()` doesn't know whether there will be 0, 1, or multiple entries read, so in general it always returns a list or iterator of some kind?  And thus in practice the inner `for` loop will only be executed once each time it is executed, for this example?

**Comment by antoninbas** [comment]
You are correct. However, the solution is needlessly complicated. The following should also work:

```python
P4Runtime sh >>>
            ...: te = table_entry['ingress.table0_control.table0']
            ...: te.counter_data.byte_count = 0
            ...: for x in te.read():
            ...:       if x.counter_data.byte_count == 0:
            ...:             print('te.counter_data.byte_count == 0 -> Generate some traffic before reading out the counters')
            ...:       else:
            ...:             print('Counter data', x.counter_data)
            ...:
```

The key thing is that the `counter_data` field should be set (or the counter data will not be returned). However, it can be set at the wildcard RPC level, and one doesn't need individual RPCs for each entry.

**Comment by antoninbas** [comment]
I have confirmed that the above solution works, so I'll update the documentation.
