### ISSUE TITLE
Should class MatchKey method `__getitem__` return value of `_`?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime-shell#105]
https://github.com/p4lang/p4runtime-shell/blob/main/p4runtime_sh/shell.py#L357-L359

```
    def __getitem__(self, name):
        _ = self._get_mf(name)
        print(self._mk.get(name, "Unset"))
```
I do not know if `_` has a special meaning in Python, but is the intent here to do `return _` at the end of this method?

**Comment by antoninbas** [comment]
The function `self._get_mf` is called for the single purpose of validating that `name` is a valid match field name for this table (i.e., that it is part of the match key). If it's not the case, it will raise a Python exception: https://github.com/p4lang/p4runtime-shell/blob/4bc4cd5c6b86a9669e5d6102da5c86ff0c0917ce/p4runtime_sh/shell.py#L348-L350.

(Technically some subset of suffixes is supported for each match field if you look at `_get_mf` in details)

The Python exception will then be translated into a user-facing error message.

The statement `_ = self._get_mf(name)` could be replaced by `self._get_mf(name)`, but I think whoever wrote the code wanted to make it clear that there is a return value but that we are deliberately ignoring it. Some code linters which warn about unused function return values prefer `_ = self._get_mf(name)` to `self._get_mf(name)`.

**Comment by jafingerhut** [comment]
More significantly, though, shouldn't a `__getitem__` method return a useful value?  This `__getitem__` method always returns `None`, I believe, which is not useful.

After experimenting a bit more, it seems to me that changing the `print(...)` to `return ...` would be quite useful.  Even more useful if the name lookup used the abbreviations table if the name is not a full match field name.
