### ISSUE TITLE
Is documentation for modifying table default action in README correct?

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime-shell#108]
It currently says:
```
Typical usage to set the default entry:
t = table_entry['<table_name>'](is_default=True)
t.action['<p1>'] = ...
...
t.action['<pM>'] = ...
# OR t.action.set(p1=..., ..., pM=...)
t.modify
```
There is nothing in that example that mentions an action _name_ anywhere, which is required in order to modify the default action in the P4Runtime write request message, yes?

I have successfully used code like this to modify the default action:
```
t = table_entry['<table_name>'](action='<action_name>')
t.is_default = True
t.action['<p1>'] = ...
...
t.action['<pM>'] = ...
# OR t.action.set(p1=..., ..., pM=...)
t.modify
```

**Comment by antoninbas** [comment]
Yes, I think you are correct. It should be `t = table_entry['<table_name>'](is_default=True)(action='<action_name>')`.

Did you confirm that trying to set an action parameter's value without providing an action name gives an error (when `is_default=True`)?

**Comment by antoninbas** [comment]
Fixed by https://github.com/p4lang/p4runtime-shell/pull/110
