### ISSUE TITLE
Access P4Runtime shell

### ISSUE THREAD

**Issue by mariamwehbe** [p4lang/p4runtime-shell#114]
Hello,
I am new to P4Runtime
when i try to access the p4runtimeshell using the following command 
util/p4rt-sh --grpc-addr localhost:50001 --config p4src/build/p4info.txt,p4src/build/bmv2.json --election-id 0,1
I got the following error:
*** Connecting to P4Runtime server at localhost:50001 ...
Traceback (most recent call last):
  File "/.../ngsdn-tutorial/util/p4rt-sh", line 114, in <module>
    main()
  File "/.../ngsdn-tutorial/util/p4rt-sh", line 85, in main
    os.mkdir(TMP_DIR)
FileExistsError: [Errno 17] File exists: '/.../ngsdn-tutorial/util/.pipe_cfg'

The first time it worked and I did access the shell. But When I restarted I am not able anymore

**Comment by antoninbas** [comment]
This error comes from this script: https://github.com/opennetworkinglab/ngsdn-tutorial/blob/advanced/util/p4rt-sh
I'll close this issue given that it is not related to this repository. I suggest that you open an issue in the ngsdn-tutorial repository (I don't know if it is actively maintained).
