### ISSUE TITLE
Problems with importing modules using p4runtime-shell in scripts

### ISSUE THREAD

**Issue by sergio-gimenez** [p4lang/p4runtime-shell#25]
I am trying to load two simple table entries to a **bmv2** switch using a python script instead of the interactive shell. Following the example in the README, I have wrote this:

```python
import p4runtime_sh.shell as sh

# you can omit the config argument if the switch is already configured with the
# correct P4 dataplane.
sh.setup(
    device_id=1,
    grpc_addr='localhost:50051',
    election_id=(0, 1), # (high, low)
    config=sh.FwdPipeConfig('p4src/build/p4info.txt', 'p4src/build/p4info.txt')
)

#TABLE ENTRIES
te = table_entry["MyIngress.efcp_lpm"](action = "MyIngress.efcp_forward")
te.match["hdr.efcp.dstAddr"] = ("1")
te.action['dstAddr'] = ("00:00:00:00:00:01")
te.action['port'] = ("1")
te.insert()


te = table_entry["MyIngress.efcp_lpm"](action = "MyIngress.efcp_forward")
te.match["hdr.efcp.dstAddr"] = ("2")
te.action['dstAddr'] = ("00:00:00:00:00:02")
te.action['port'] = ("2")
te.insert()

sh.teardown()
```

But something wrong is going with the imports, because I got the following message when I try to run the script:

```
Traceback (most recent call last):
  File "testImport.py", line 1, in <module>
    import p4runtime_sh.shell as sh
  File "/home/p4/rinap4controlplane/p4runtime_sh/shell.py", line 25, in <module>
    from p4runtime_sh.p4runtime import P4RuntimeClient, P4RuntimeException, parse_p4runtime_error
  File "/home/p4/rinap4controlplane/p4runtime_sh/p4runtime.py", line 18, in <module>
    from google.rpc import status_pb2, code_pb2
ImportError: No module named 'google.rpc'
```

Where can I find this `google.rpc` missing module? I tried to google it, but I can't find any working solution.

**Comment by antoninbas** [comment]
This module is provided by the `grpcio` Python package. I recommend installing version 1.17.2 with pip if possible.

**Comment by sergio-gimenez** [comment]
I already had installed the `grpcio` package. I uninstalled, tried to install the `1.17.2` version but  pip says that this version does not exists:

```
$ pip install grpcio==1.17.2
Collecting grpcio==1.17.2
  Could not find a version that satisfies the requirement grpcio==1.17.2 (from versions: 0.4.0a0, 0.4.0a1, 0.4.0a2, 0.4.0a3, 0.4.0a4, 0.4.0a5, 0.4.0a6, 0.4.0a7, 0.4.0a8, 0.4.0a13, 0.4.0a14, 0.5.0a0, 0.5.0a1, 0.5.0a2, 0.9.0a0, 0.9.0a1, 0.10.0a0, 0.11.0b0, 0.11.0b1, 0.12.0b0, 0.13.0, 0.13.1rc1, 0.13.1, 0.14.0rc1, 0.14.0, 0.15.0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.2rc0, 1.0.2, 1.0.3, 1.0.4, 1.1.0rc1, 1.1.0, 1.1.3, 1.2.0rc1, 1.2.0rc2, 1.2.0, 1.2.1, 1.3.0, 1.3.3, 1.3.5, 1.4.0rc1, 1.4.0, 1.6.0rc1, 1.6.0, 1.6.3, 1.7.0rc1, 1.7.0, 1.7.3, 1.8.0rc1, 1.8.0rc2, 1.8.0rc3, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.6, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1rc1, 1.10.1rc2, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.12.0rc1, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0rc3, 1.13.0, 1.14.0rc1, 1.14.0rc2, 1.14.0, 1.14.1, 1.14.2rc1, 1.14.2, 1.15.0rc1, 1.15.0, 1.16.0rc1, 1.16.0, 1.16.1rc1, 1.16.1, 1.17.0rc1, 1.17.0, 1.17.1rc1, 1.17.1, 1.18.0rc1, 1.18.0, 1.19.0rc1, 1.19.0, 1.20.0rc1, 1.20.0rc2, 1.20.0rc3, 1.20.0, 1.20.1, 1.21.0rc1, 1.21.1rc1, 1.21.1, 1.22.0rc1, 1.22.0, 1.22.1, 1.23.0rc1, 1.23.0, 1.23.1, 1.24.0rc1, 1.24.0, 1.24.1)
No matching distribution found for grpcio==1.17.2
```

**Comment by antoninbas** [comment]
This project uses Python 3, not Python 2, so you probably need `pip3`.

Any 1.17.x version should be fine.

**Comment by antoninbas** [comment]
You can look at the Dockerfile to see which dependencies are required: https://github.com/p4lang/p4runtime-shell/blob/master/Dockerfile

**Comment by sergio-gimenez** [comment]
So, I installed all the packages listed in [requeriments.txt](https://github.com/p4lang/p4runtime-shell/blob/master/requirements.txt) (including `grpcio` in version `1.17.0`) and it still complains saying: `ImportError: No module named 'google.rpc'`.

I also tried to run the script inside the docker, but it didn't work either.

I am a bit lost about possible solutions. Any other clues?

**Comment by antoninbas** [comment]
Sorry my bad I misread the issue the first time. The error has nothing to do with the `grpcio` package. These Python files (`google.rpc.status_pb2` and `google.rpc.code_pb2`) are generated from proto files and then installed. This rule in the Docker takes care of it: https://github.com/p4lang/p4runtime-shell/blob/master/Dockerfile#L33. You will notice that there is a also a hack in the Dockerfile to make the import work: https://github.com/p4lang/p4runtime-shell/blob/master/Dockerfile#L45

Running inside the docker should work fine (I just checked) but you need to make sure you activate the virtualenv:
```
abas@ubuntu:/tmp$ docker run -ti --entrypoint "" p4lang/p4runtime-sh bash
root@25a0a1759a36:/p4runtime-sh# source $VENV/bin/activate
(venv) root@25a0a1759a36:/p4runtime-sh# python3 -c "import p4runtime_sh.shell as sh"
(venv) root@25a0a1759a36:/p4runtime-sh# echo $?
0
```

If you want to run your script outside the docker, you may have more work ahead of you... Reproducing all the steps inside the Dockerfile (including using a virtualenv) should work. If you don't want to do that, installing this repo should fix the import issue: https://github.com/p4lang/PI

**Comment by sergio-gimenez** [comment]
Thank you a lot for this @antoninbas. It worked :smiley: 

> ```
> abas@ubuntu:/tmp$ docker run -ti --entrypoint "" p4lang/p4runtime-sh bash
> root@25a0a1759a36:/p4runtime-sh# source $VENV/bin/activate
>(venv) root@25a0a1759a36:/p4runtime-sh# python3 -c "import p4runtime_sh.shell as sh"
> (venv) root@25a0a1759a36:/p4runtime-sh# echo $?
> 0
>```

But now I am struggling with another error, that it also might be related with importing stuff. 

I activate the virtualenv inside the docker. I run the script I posted avobe and the `setup()` method works. But then I got this error:

```python
Traceback (most recent call last):
  File "runtime-shell.py", line 15, in <module>
    te = table_entry["MyIngress.efcp_lpm"](action = "MyIngress.efcp_forward")
NameError: name 'table_entry' is not defined
```

It seems like it can't find the `table_entry` command. Any suggestions?

**Comment by antoninbas** [comment]
should be `sh.TableEntry`, just like in the README

**Comment by sergio-gimenez** [comment]
True, sorry. 😅 

Working now, looks like the issue can be closed?
