### ISSUE TITLE
Trying to handle packets between data plane and control plane using p4runtime-shell

### ISSUE THREAD

**Issue by sergio-gimenez** [p4lang/p4runtime-shell#26]
I am trying to send and receive packets between the switch and the CPU, i.e communication between data plane and control plane.

On the switch I am running **bmv2 with stratum**. I am working with the [opennetworking/mn-stratum](https://hub.docker.com/r/opennetworking/mn-stratum) docker image.

On the other side, I am using the [p4lang/p4runtime-shell](https://hub.docker.com/r/p4lang/p4runtime-sh) docker image to load pipeline configuration and push table entries.

As far as I know, in order to send packets to the CPU, I just need to forward packets to the egress port that corresponds to the CPU port specified in the `--cpu port` argument when running the bmv2 switch. So that's what I do in my p4 program in the ingress processing:

```p4
standard_metadata.egress_spec = CPU_PORT;
```

But now I want to handle this packet in the CPU and I do not know really how to do it. I don't even know what happens when I send the packet, because I'm not able to see the bmv2 log properly (already asked here https://github.com/stratum/stratum/issues/21).

Also, I do not know how to send packets from the control plane to the data plane using p4runtime-shell.

So I am a bit lost here. Any clues about how can I handle in/out packets?

**Comment by antoninbas** [comment]
p4runtime-shell does not support injecting / receiving CPU packets at the moment.

If you send a packet to the CPU port in your P4 program, it will be sent on the P4Runtime stream channel to the master controller. If you are using p4runtime-shell to add entries, then p4runtime-shell is the master controller and it will receive the CPU packets. However it currently does not do anything with the received packets (such as print them). I believe it enqueues them in a Python queue, so you may run out of memory at some point...

I believe the user should be given an option as to what to do with these packets (when the p4runtime-shell is the P4Runtime master). These options could include:
 * drop all packets
 * apply a Python function of the user choice to every packet (that function could be just a print although I would recommend not doing that)
 * write the packets to a file on disk that the user can monitor with `tail -f`

Sending CPU packets is easy, we just need to add a new shell command for that.

I will take a stab at it over the weekend if I get some time.

**Comment by drobinkent** [comment]
I think, the stream_out_q works with the rpc requests only. 
Is there any extra code needed to send packet_out message to switch?

**Comment by IMxbo** [comment]
@drobinkent @sergio-gimenez 
first, you should define the controller headers in your p4 code, like this:
```p4
@controller_header("packet_in")
header packet_in_t {
    bit<9> ingress_port;
    bit<7> padding;
}

@controller_header("packet_out")
header packet_out_t {
    bit<9> egress_port;
    bit<7> padding;
}
```
then, you can send packets to switch in your python code like this:
```python
def sendPacketToDataPlane():
    pktInRaw = send_pkt.getPacktInRaw()
    req = p4runtime_pb2.StreamMessageRequest()
    packet = p4runtime_pb2.PacketOut()
    packet.payload = pktInRaw
    
    metadata = p4runtime_pb2.PacketMetadata()
    metadata.metadata_id=1
    metadata.value = (1).to_bytes(2,'big')
    packet.metadata.append(metadata)
    metadata.metadata_id=2
    metadata.value = (0).to_bytes(2,'big')
    packet.metadata.append(metadata)
    req.packet.CopyFrom(packet)

    # another way to set packet field
    # packet = req.packet
    # packet.payload = pktInRaw

    # another way to add metada fields, 
    # ref:https://developers.google.com/protocol-buffers/docs/reference/python-generated#repeated-fields
  
    # metadata = req.packet.metadata.add()
    # metadata.metadata_id = 1
    # metadata.value = (1).to_bytes(2,'big')
    # metadata = req.packet.metadata.add()
    # metadata.metadata_id = 2
    # metadata.value = (0).to_bytes(2,'big')


    sh.client.stream_out_q.put(req)
```
receive packets from switch is easier,
```python
def receivePacketFromDataPlane():
    send_pkt.sendPacket('send_to_cpu')
    rep = sh.client.get_stream_packet('packet',timeout=2)
    if rep is not None:
        print('ingress port is',int.from_bytes(rep.packet.metadata[0].value,'big'))
```
I didn't do extensive tests, but a single test showed that this was able to exchange packets between the data plane and  control plane. Is there any problem with this use? @antoninbas

**Comment by antoninbas** [comment]
@IMxbo that looks correct. I am keeping this issue open because I think the shell should provide a more user-friendly way to send and receive packets. For example, with the right helper functions, your example could read:
```
sh.client.send_packet_out(metadata = {"egress_port": <byte string>}, payload = <packet payload>)
```

I also want to find a way to deal with packet in messages received from the server. We can't just buffer them forever, and it's unclear to me how to deal with them when the shell is used in an interactive fashion (i.e. non-programmatically).

**Comment by jafingerhut** [comment]
Something that seems like it might be easy to supply as features in the shell, and might be useful, would be to maintain a list of received packets that users can do these kinds of operations on interactively:

+ access any packet anywhere in the received list, perhaps appearing like a Python list, perhaps implementing all of the same Python methods of accessing it as for a built-in list, e.g. received_pkts[0], received_pkts[2:4], etc.
+ return and remove the first packet
+ clear the list of received packets
