### ISSUE TITLE
Trying to follow one install method from README, but it is failing

### ISSUE THREAD

**Issue by jafingerhut** [p4lang/p4runtime-shell#27]
I started with a freshly installed Ubuntu 16.04.6 Linux VM, 50GBytes of free disk space, 4G RAM, 4 virtual CPUs, on a host machine with more than that of all of those things.

First I installed docker using this script (only 4 "interesting" lines in the middle): https://github.com/jafingerhut/p4-guide/blob/master/bin/install-docker.sh#L14-L17

I shutdown and rebooted the VM for the 'usermod' command at the end to take effect.

Then I ran this script (only 3 "interesting" lines in the middle): https://github.com/jafingerhut/p4-guide/blob/master/bin/install-p4runtime-shell.sh#L9-L11

it goes through many steps in a way that looks successful, until I see this output near the end of the output: https://github.com/jafingerhut/p4-guide/blob/master/bin/output/log-p4runtime-shell.txt#L499-L501

Do you see any incorrect commands I am running, or is the problem with the commands in the Dockerfile?

**Comment by jafingerhut** [comment]
I had cloned this repo without using the `--recursive` option, so did not pick up the p4runtime repo files that are needed for the docker image build to succeed.  Suggested update to the README's build instructions are in this PR: https://github.com/p4lang/p4runtime-shell/pull/28

**Comment by antoninbas** [comment]
Fixed by #28 (thanks Andy!)

I'll just add - for people that stumble upon this issue - that unless you are making changes to the code, it's probably simpler to just use the pre-built Docker image hosted on Dockerhub (instructions in the README). I make sure the image size stays fairly small.
