### ISSUE TITLE
google.rpc  module not found

### ISSUE THREAD

**Issue by drobinkent** [p4lang/p4runtime-shell#32]
When I try to run the system without docker in my native ubuntu, it says following error. Is it because of some kind of dependency mismatch in PI? 

Traceback (most recent call last):
  File "shell.py", line 25, in <module>
    from p4runtime import P4RuntimeClient, P4RuntimeException, parse_p4runtime_error
  File "/home/deba/Desktop/p4runtime-shell/p4runtime_sh/p4runtime.py", line 18, in <module>
    from google.rpc import status_pb2, code_pb2
ModuleNotFoundError: No module named 'google.rpc'

I have seen a some post to this kind of error in some version of p4tutorial. But I could not resolve the issue. Later I moved to the provided VM. Can anyone please help me to resolve the issue. I want to run the p4runtime shell directly in ubuntu.

**Comment by antoninbas** [comment]
It's probably much easier to install docker on your system and run the shell as a docker container, than to try to install all the dependencies correctly...

If you still want to run everything natively, I suggest going through this thread to check if the solution works for you: https://github.com/p4lang/p4runtime-shell/issues/25. In particular look at this comment I posted: https://github.com/p4lang/p4runtime-shell/issues/25#issuecomment-542347497

**Comment by drobinkent** [comment]
Thanks. I am checking that. One more question: Does this p4runtime shell support meter read write? Because each time I want to write a meter entry or read a meter entry, I see some error.

**Comment by antoninbas** [comment]
Yes meters, are supported: https://github.com/p4lang/p4runtime-shell/blob/master/p4runtime_sh/test.py#L722

Hopefully you are getting a helpful error message.

**Comment by drobinkent** [comment]
I was trying to use the code as  standalone controller. I was basically trying to add meter support to onos. Then after failure I moved to p4runtime project. Both the place I am stuck on grpc related issue. 

I have modified the shell.py code, and after trying to setup the forwardingpipelineconfig. I get the following error. 

> 
> CRITICAL:root:Error when setting config
> CRITICAL:root:P4Runtime RPC error (UNKNOWN): Error in first phase of device update
> CRITICAL:root:Exception inP4Runtime RPC error (UNKNOWN): Error in first phase of device update


Can you kindly, tell me what is the possible cause? 

While I was trying to read a meter using the docker version I was getting "unimplemented error" .

**Comment by antoninbas** [comment]
A few "wildcard" operations are not supported for meters, but the error message should let you know which one.

Why do think the error is with the P4Info file and not with the bmv2 JSON file?

**Comment by drobinkent** [comment]
Sorry, that was a stupid mistake as there was a problem with my bmv2.json. 

Another issue, 

I am trying to modify a meter 

> 
> me = sh.MeterEntry(meter_name="my_meter_indirect")
> me.cir = 3
> me.__setattr__("index",4)
> me.modify()

The bmv2 switch shows in log, 

> 
> evice_id: 1
> election_id {
>   low: 1
> }
> updates {
>   type: MODIFY
>   entity {
>     meter_entry {
>       meter_id: 335567108
>       index {
>         index: 4
>       }
>       config {
>         cir: 3
>       }
>     }
>   }
> }
> 
> 

But the python script says

> 
> raceback (most recent call last):
>   File "Mycontroller.py", line 23, in <module>
>     me.modify()
>   File "/home/deba/Desktop/p4runtime-shell/p4runtime_sh/shell.py", line 660, in modify
>     self._write(p4runtime_pb2.Update.MODIFY)
>   File "/home/deba/Desktop/p4runtime-shell/p4runtime_sh/shell.py", line 644, in _write
>     client.write_update(update)
>   File "/home/deba/Desktop/p4runtime-shell/p4runtime_sh/p4runtime.py", line 124, in handle
>     raise P4RuntimeWriteException(e) from None
> p4runtime_sh.p4runtime.P4RuntimeWriteException: Error(s) during Write:
> 	* At index 0: UNKNOWN, 'Error when writing meter spec'

I understand that, wild card write of meter si not supported. But here I am setting the index. But still the problem persists.

**Comment by Illakiyavarshini** [comment]
when i was installing gRPC from "https://github.com/p4lang/PI/tree/main" i got the version as 
"~/grpc/cmake/build$ pkg-config --modversion grpc
which grpc_cpp_plugin
ls /usr/local/lib/pkgconfig | grep grpc
21.0.0
/usr/local/bin/grpc_cpp_plugin
grpc++.pc
grpc.pc
grpc++_unsecure.pc
grpc_unsecure.pc"

but the actual version given is "[gRPC v1.43.2]" is version 21.0.0 is compatible with PI and P4Runtime?

**Comment by jafingerhut** [comment]
I do not have a complete list of compatible versions to share with you, unfortunately.

I do have instructions for installing p4c, behavioral-model, PI, p4runtime, p4runtime-shell, and a few other open source P4 development-related repositories on Ubuntu 20.04, 22.04, and 24.04 that I can share with you, and you can use as you like (or not): https://github.com/p4lang/tutorials?tab=readme-ov-file#obtaining-required-software

**Comment by Illakiyavarshini** [comment]
Thank you so much for sharing the link. I will check that.

**Comment by Illakiyavarshini** [comment]
Thank you for the link. Definitely I will check the link.
