### ISSUE TITLE
Error running Docker version on macOS 

### ISSUE THREAD

**Issue by pudelkoM** [p4lang/p4runtime-shell#35]
When using the Docker convenience script on MacOS, Docker will complain about the mount path:

```bash
> ./p4runtime-sh-docker --grpc-addr 10.128.13.201:28000 --device-id 1 --election-id 0,1 --config /Users/max/projects/stratum/p4info.pb.txt,/Users/max/projects/stratum/pipeline_config.bin
docker: Error response from daemon: Mounts denied:
The path /var/folders/k9/j5gmsz8j0bj3hd7vxy00dm5m0000gn/T/tmpvas2pu4t
is not shared from OS X and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> File Sharing.
See https://docs.docker.com/docker-for-mac/osxfs/#namespaces for more info.
.
```

The problem is here: https://github.com/p4lang/p4runtime-shell/blob/master/p4runtime-sh-docker#L71
Which generates a path outside of the [default allowed ones](https://docs.docker.com/docker-for-mac/osxfs/#namespaces): 

> By default, you can share files in /Users/, /Volumes/, /private/, and /tmp directly. 

Just for testing I replace it with this and it worked just fine:

```diff
diff --git a/p4runtime-sh-docker b/p4runtime-sh-docker
index 017030c..f92bb9c 100755
--- a/p4runtime-sh-docker
+++ b/p4runtime-sh-docker
@@ -68,7 +68,7 @@ def main():
         fname_p4info = "p4info.pb.txt"
         fname_bin = "config.bin"

-        tmpdir = tempfile.mkdtemp()
+        tmpdir = "/tmp/p4rt-shell" #tempfile.mkdtemp()
         logging.debug(
             "Created temporary directory '{}', it will be mounted in the docker as '{}'".format(
                 tmpdir, mount_path))
```

Is using Docker on Mac simple not supported?

**Comment by antoninbas** [comment]
It's just never been tested on macOS.

I'm fine with using `tempfile.mkdtemp(dir="/tmp")` since `/tmp` seems to be shared by default with the hyperkit VM used by docker. That will work on both Linux and macOS. If you want to open a PR, that would be great.
