### ISSUE TITLE
Correct the link 

### ISSUE THREAD

**Issue by dkalog** [p4lang/p4runtime-shell#46]
The link for  [fabric.p4](https://github.com/opennetworkinglab/onos/blob/master/pipelines/fabric/impl/src/main/resources/fabric.p4)  in the line _Here is some of what you can do when using p4runtime-sh with ONF's_ [fabric.p4](https://github.com/opennetworkinglab/onos/blob/master/pipelines/fabric/src/main/resources/fabric.p4).

should be  

https://github.com/opennetworkinglab/onos/blob/master/pipelines/fabric/impl/src/main/resources/fabric.p4

**Comment by antoninbas** [comment]
Thanks for reporting this. I updated the link as suggested.

I see that fabric.p4 received some updates in July. Hopefully the examples in the README are still up-to-date. It seems that the update mostly affected the SPGW implementation, so we should be good.
