### ISSUE TITLE
Adopt more inclusive terminology

### ISSUE THREAD

**Issue by antoninbas** [p4lang/p4runtime-shell#57]
A lot of open-source projects and organizations are now opting to ban non-inclusive terms: master/slave, whitelist/blacklist, etc.

- The [Inclusive Naming Initiative](https://inclusivenaming.org/) launched recently, with members such as the Linux Foundation, the CNCF and various companies. Several [related projects](https://inclusivenaming.org/related-projects/) have also come into existence.

- My employer, VMware, has publicly [committed](https://www.vmware.com/company/news/updates/replacing-problematic-terminology.html) to adopting inclusive terminology.

- The Linux Kernel coding style was updated a couple months back to advocate against using non-inclusive terminology and provide some alternative suggestions to the terms most commonly used: https://github.com/torvalds/linux/blob/master/Documentation/process/coding-style.rst#4-naming

We should therefore make the following changes as soon as possible:

- [x] Adopt inclusive terminology everywhere in code and documentation - this should match the changes to the P4Runtime spec (https://github.com/p4lang/p4runtime/pull/320) -> #59 
- [x] Rename the "master" git branch for the repository to "main"

**Which words should be replaced?**

The consensus is that at the very least "master/slave" and "whitelist/blacklist" should not be used. The IETF identifies some additional terms / metaphors (https://tools.ietf.org/id/draft-knodel-terminology-00.html) and notably recommends using the neuter "they" as the singular pronoun.

We also would like to avoid the following terms when possible: abort, kill, blackout, segregate/segregation

**Comment by jnfoster** [comment]
This is great.

If you can suggest a playbook for other p4lang repos, I'd be glad to put them into action.

**Comment by antoninbas** [comment]
@jnfoster I just try to follow the recommendations from https://inclusivenaming.org/language/word-list/ and https://tools.ietf.org/id/draft-knodel-terminology-00.html

I have been making my way through the repos I'm most involved with, and I took care of p4runtime, bmv2, PI and now this one.
