### ISSUE TITLE
Cannot read meter rates

### ISSUE THREAD

**Issue by jurijnota** [p4lang/p4runtime-shell#65]
Because of a typo [here](https://github.com/p4lang/p4runtime-shell/blob/eb32e419e2bbd8a05b2032a1e6e71b932b3368e0/p4runtime_sh/shell.py#L1868), meter rates cannot be read properly. Indeed, `_MeterConfig.get_count` method is used to retrieve them, while class `_MeterConfig` has no such method (which belongs to `_CounterConfig`).

_Solution_
Replacing `_MeterConfig.get_count` with `_MeterConfig.get_param` should solve the issue.

**Comment by jurijnota** [comment]
> Because of a typo [here](https://github.com/p4lang/p4runtime-shell/blob/eb32e419e2bbd8a05b2032a1e6e71b932b3368e0/p4runtime_sh/shell.py#L1868), meter rates cannot be read properly. Indeed, `_MeterConfig.get_count` method is used to retrieve them, while class `_MeterConfig` has no such method (which belongs to _CounterConfig).
> 
> _Solution_
> Replacing `_MeterConfig.get_count` with `_MeterConfig.get_param` should solve the issue.

**Comment by antoninbas** [comment]
Thanks for reporting this. Do you think you could open a PR to address this issue?

**Comment by jurijnota** [comment]
I just created a pull request with the fix proposed.
