### ISSUE TITLE
Unrecognized argument in launching the shell with docker

### ISSUE THREAD

**Issue by JBarcellesi** [p4lang/p4runtime-shell#78]
I am trying to launch the p4rt shell with docker on the exercises in the tutorials (https://github.com/p4lang/tutorials/tree/master/exercises/p4runtime) with the command :

[sudo] docker run -ti -v ../tutorials/exercises/p4runtime/build/:/tmp/ p4lang/p4runtime-sh --grpc-addr 172.17.0.1:50051 \
 --device-id 0 --election-id 0,1 \
 --config /tmp/advanced_tunnel.p4.p4info.txt, /tmp/advanced_tunnel.json

but I got "unrecognized argument: /tmp/advanced_tunnel.json"

These are the two files that the P4 compiler creates when I launch the exercise. I also tried:

[sudo] ./p4runtime-sh-docker --grpc-addr 172.17.0.1:50051 \
  --device-id 0 --election-id 0,1 \
  --config ../tutorials/exercises/p4runtime/build/advanced_tunnel.p4.p4info.txt, ../tutorials/exercises/p4runtime/build/advanced_tunnel.json

and I got " CRITICAL: root: " " is not a valid file"

Since on the README, there is written to use the bmv2.json file created by the compiler, I cannot understand where is the problem. 

Does anyone know how to fix it?

P.S. I also tried 9559 as the port number, but I got the same result.

**Comment by antoninbas** [comment]
looks like you have a whitespace between the 2 files, so it would be interpreted as 2 command-line arguments instead of 1: `--config /tmp/advanced_tunnel.p4.p4info.txt, /tmp/advanced_tunnel.json`

**Comment by JBarcellesi** [comment]
Thank you, now it's working.
