### ISSUE TITLE
At index 0: UNKNOWN, 'Error when adding match entry to target'

### ISSUE THREAD

**Issue by Finnonto** [p4lang/p4runtime-shell#79]
hello, i was trying to insert an ternary entry through P4runtime shell like :

global_options["canonical_bytestrings"] = False
te = table_entry["EgressPipeImpl.interpolation_exp_Table"](action="EgressPipeImpl.interpolation_exp_cal")
te.match["local_metadata.hash_result"] = '0x0400 &&& 0xfc00'
te.action["y1"] = "0x04222b5f"
te.action["y2"] = "0x04244725"
te.action["x_alpha"] = "0x0400"
te.action["shifter"] = "10"
te.insert()

and it the error message sais that the priority number must not be zero ,cause it's a ternary entry ,so i set the priority to 1 like 
global_options["canonical_bytestrings"] = False
te = table_entry["EgressPipeImpl.interpolation_exp_Table"](action="EgressPipeImpl.interpolation_exp_cal")
te.match["local_metadata.hash_result"] = '0x0400 &&& 0xfc00'
te.action["y1"] = "0x04222b5f"
te.action["y2"] = "0x04244725"
te.action["x_alpha"] = "0x0400"
te.action["shifter"] = "10"
te.priority = 1
te.insert()

and it return an error message:  * At index 0: UNKNOWN, 'Error when adding match entry to target' 

full text is:
---------------------------------------------------------------------------
P4RuntimeWriteException                   Traceback (most recent call last)
<ipython-input-3-e8c21db410da> in <module>
      7 te.action["shifter"] = "10"
      8 te.priority = 1
----> 9 te.insert()

/p4runtime-sh/venv/lib/python3.8/site-packages/p4runtime_shell-0.0.1-py3.8.egg/p4runtime_sh/shell.py in insert(self)
    679             raise NotImplementedError("Insert not supported for {}".format(self._entity_type.name))
    680         logging.debug("Inserting entry")
--> 681         self._write(p4runtime_pb2.Update.INSERT)
    682 
    683     def delete(self):

/p4runtime-sh/venv/lib/python3.8/site-packages/p4runtime_shell-0.0.1-py3.8.egg/p4runtime_sh/shell.py in _write(self, type_)
    673         update.type = type_
    674         getattr(update.entity, self._entity_type.name).CopyFrom(self._entry)
--> 675         client.write_update(update)
    676 
    677     def insert(self):

/p4runtime-sh/venv/lib/python3.8/site-packages/p4runtime_shell-0.0.1-py3.8.egg/p4runtime_sh/p4runtime.py in handle(*args, **kwargs)
    121             if e.code() != grpc.StatusCode.UNKNOWN:
    122                 raise e
--> 123             raise P4RuntimeWriteException(e) from None
    124     return handle
    125 

P4RuntimeWriteException: Error(s) during Write:
	* At index 0: UNKNOWN, 'Error when adding match entry to target'

**Comment by antoninbas** [comment]
For this kind of error, you probably want to take a look at the switch logs (I assume it's bmv2)

**Comment by Finnonto** [comment]
may I ask a silly question ? How to check the switch log

**Comment by antoninbas** [comment]
Looks like you are using Stratum, the logs would be in the logs of the stratum_bmv2 process. Can't really help you more than that, you may have to do some digging or ask them directly.

This is a pretty rare error, so curious to know what it is. I actually can't tell from your post which `action` you are using for the table entry?

**Comment by Finnonto** [comment]
thank for your kindness, I'm trying to make a simple interpolation calculation in p4 dataplane,

BTW , do you know how to parse "p4runtime_pb2." StreamMessageResponse" like \001,\000\000 or \001\030\300\000, I've tried to use btyearray  with utf8 encodeing  to decode ,but it seems not work to me.

**Comment by antoninbas** [comment]
in case that wasn't clear, let me repeat my last question:
```
global_options["canonical_bytestrings"] = False
te = table_entry"EgressPipeImpl.interpolation_exp_Table"
te.match["local_metadata.hash_result"] = '0x0400 &&& 0xfc00'
te.action["y1"] = "0x04222b5f"
te.action["y2"] = "0x04244725"
te.action["x_alpha"] = "0x0400"
te.action["shifter"] = "10"
te.insert()
```
where do you specify the action name?

**Comment by antoninbas** [comment]
> BTW , do you know how to parse "p4runtime_pb2." StreamMessageResponse" like \001,\000\000 or \001\030\300\000, I've tried to use btyearray in Python with utf8 encodeing to decode ,but it seems not work to me.

I don't know what that is. `StreamMessageResponse` has several fields which are grouped in a Protobuf `oneof`. You can refer to the Protobuf Python documentation and to `p4runtime.proto`.

**Comment by Finnonto** [comment]
sorry, i miss the action .


te = table_entry["EgressPipeImpl.interpolation_exp_Table"](action="EgressPipeImpl.interpolation_exp_cal")
te.match["local_metadata.hash_result"] = '0x0400 &&& 0xfc00'
te.action["y1"] = "0x04222b5f"
te.action["y2"] = "0x04244725"
te.action["x_alpha"] = "0x0400"
te.action["shifter"] = "10"
te.priority = 1
te.insert()


thank for your info about `StreamMessageResponse`
