### ISSUE TITLE
Support secure channel grpc with SSL

### ISSUE THREAD

**Issue by pradeepvdevan** [p4lang/p4runtime-shell#84]
Please support secure channel grpc with SSL credentials(ssl_channel_credentials) and any Auth metadata as optional AAA authentication?

**Comment by antoninbas** [comment]
@pradeepvdevan I opened a PR to support server TLS authentication.

However, if you want client authentication to be supported as well, there are different options and you'll have to expand on what you are asking for:
1) are you looking for mutual authentication using client certificates?
2) are you looking for some custom authentication using metadata credentials (https://grpc.io/docs/guides/auth/#extending-grpc-to-support-other-authentication-mechanisms).

Based on your question, it seems that are interested in 2).
However, P4Runtime doesn't define standard authentication mechanism for clients, so not sure what you expect us to implement. If you have a standard in mind, please share some relevant pointers.

**Comment by pradeepvdevan** [comment]
Hi Antonin,

Thanks for looking into this.
Option 1 seems good with certs(root_certificate, certificate_chain and key).
I do have option 2 implemented with the AuthMetaData plugin(eg AAA
username/password) along with option 1. But yes, as you mentioned option 2
is not a standard and could be left to users.

Thanks,
Pradeep

**Comment by antoninbas** [comment]
I merged support for mutual TLS authentication. If there is a need for a different client authentication mechanism, it should be discussed and standardized with the P4 API Working Group.
