### ISSUE TITLE
Latest p4runtime-shell release doesn't include TLS support 

### ISSUE THREAD

**Issue by jokuniew** [p4lang/p4runtime-shell#99]
Latest release of p4runtime-shell on PyPI was on Dec 2th 2020 https://pypi.org/project/p4runtime/1.3.0/#history

TLS support was added on January 22th 2022 https://github.com/p4lang/p4runtime-shell/commit/aba1428c7b54a2e2e01b49cd5c0461ce143113b4

There was no release on Github/PyPI since 2020.
Suggested solution: release the package or create CI with automatic solution.

Issue related to this community conversation https://p4-lang.slack.com/archives/C8ZR5EN3F/p1662711260355929

@Yi-Tseng @antoninbas

**Comment by antoninbas** [comment]
Done, version v0.0.3 was pushed to PyPI
